name: deploy to S3
description: 'Deploy a static website via AWS S3.'
runs:
  using: docker
  image: Dockerfile
inputs:
  bucket-name:
    description: S3 bucket name
    required: true
  bucket-region:
    description: S3 region
    required: false
    default: eu-central-1
  dist-folder:
    description: The folder containing the deployable files.
    required: true
outputs:
  website-url:
    description: The URL of the deployed site.
